name: Check Jupyter Notebooks

on: [push, pull_request]

jobs:
  ensure_clean_jupyter_notebooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      with:
        disable-checks: execution_count
