name: Check Jupyter Notebooks

on: [push, pull_request]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install jq


    - name: Determine Base Reference
      id: determine-base-ref
      run: |
        echo "Determining base reference..."
        if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
          echo "Thinks there is a parent commit"
          base_ref=$(git merge-base HEAD HEAD^)
        else
          echo "Thinks there is no parent commit"
          base_ref=$(git rev-list --max-parents=0 HEAD)

        fi
        echo "Base reference is: $base_ref"
        echo "base_ref=$base_ref" >> $GITHUB_ENV

    - name: Find Jupyter Notebooks with output data
      id: find-notebooks
      run: |
        base_ref=${{ env.base_ref}}
        echo "Using base reference: $base_ref
        files_with_output=$(git diff --name-only $base_ref HEAD | grep '.ipynb' || true)

        if [ -n "$files_with_output" ]; then
          echo "Checking the following files for output data:"
          echo "$files_with_output"
          for file in $files_with_output; do
            if jq '.cells[].outputs | length' "$file" | grep -v '^0$' > /dev/null; then
              echo "File $file contains output data"
              exit 1
            fi
          done
        else
          echo "No Jupyter Notebook files with output data found."
        fi
