name: Check Jupyter Notebooks

on: [push, pull_request]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get install jq

    - name: Find Jupyter Notebooks with output data
      run: |
        # Determine the base reference for comparison
        if [ -z "$(git rev-parse --verify HEAD^ 2>/dev/null)" ]; then
          base_ref=$(git rev-list --max-parents=0 HEAD)
        else
          base_ref=$(git merge-base HEAD HEAD^)
        fi

        # Get the list of changed .ipynb files
        files_with_output=$(git diff --name-only $base_ref HEAD | grep '.ipynb' || true)

        if [ -n "$files_with_output" ]; then
          echo "Checking the following files for output data:"
          echo "$files_with_output"

          for file in $files_with_output; do
            if jq '.cells[].outputs | length' "$file" | grep -v '^0$' > /dev/null; then
              echo "File $file contains output data"
              exit 1
            fi
          done
        fi
